// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.ibm.isc.customerfulfillment.bhoppt.service.reportmgr;

import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.CompareTPReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ContractAmendmentReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ContractAttachmentReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ContractPlanningReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.DeletedSWOReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.DeletedUsersReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.InventoryListReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ListEntitledPricesReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ProposalCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ReportsCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ReverificationReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.SysplexReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.VarianceRptCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.exception.ServiceException;
import com.ibm.isc.customerfulfillment.bhoppt.util.customdto.BaseAgreementReportCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.util.customdto.BaseAgreementReportsCustomDTO;
import java.lang.Object;
import java.lang.String;
import java.lang.Throwable;
import java.rmi.Remote;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Tie;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.ORB;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.Delegate;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.ResponseHandler;
import org.omg.CORBA.portable.UnknownException;

public class _EJSRemoteStatelessReportManager_9f8cce5a_Tie extends org.omg.CORBA_2_3.portable.ObjectImpl implements Tie {
    
    private EJSRemoteStatelessReportManager_9f8cce5a target = null;
    private ORB orb = null;
    
    private static final String[] _type_ids = {
        "RMI:com.ibm.isc.customerfulfillment.bhoppt.service.reportmgr.ReportManager:0000000000000000", 
        "RMI:javax.ejb.EJBObject:0000000000000000", 
        "RMI:com.ibm.websphere.csi.CSIServant:0000000000000000", 
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public void setTarget(Remote target) {
        this.target = (EJSRemoteStatelessReportManager_9f8cce5a) target;
    }
    
    public Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return this;
    }
    
    public void deactivate() {
        if (orb != null) {
            orb.disconnect(this);
            _set_delegate(null);
        }
    }
    
    public ORB orb() {
        return _orb();
    }
    
    public void orb(ORB orb) {
        orb.connect(this);
    }
    
    public void _set_delegate(Delegate del) {
        super._set_delegate(del);
        if (del != null)
            orb = _orb();
        else
            orb = null;
    }
    
    public String[] _ids() { 
        return (String [] )  _type_ids.clone();
    }
    
    public OutputStream _invoke(String method, InputStream _in, ResponseHandler reply) throws SystemException {
        try {
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.length()) {
                case 6: 
                    if (method.equals("remove")) {
                        return remove(in, reply);
                    }
                case 11: 
                    if (method.equals("_get_handle")) {
                        return _get_handle(in, reply);
                    } else if (method.equals("isIdentical")) {
                        return isIdentical(in, reply);
                    }
                case 12: 
                    if (method.equals("_get_EJBHome")) {
                        return _get_EJBHome(in, reply);
                    }
                case 13: 
                    if (method.equals("listProposals")) {
                        return listProposals(in, reply);
                    } else if (method.equals("getSysplexRpt")) {
                        return getSysplexRpt(in, reply);
                    }
                case 15: 
                    if (method.equals("_get_primaryKey")) {
                        return _get_primaryKey(in, reply);
                    } else if (method.equals("getCompareTPRpt")) {
                        return getCompareTPRpt(in, reply);
                    } else if (method.equals("getAllBAReports")) {
                        return getAllBAReports(in, reply);
                    }
                case 16: 
                    if (method.equals("getDeletedSWORpt")) {
                        return getDeletedSWORpt(in, reply);
                    } else if (method.equals("checkForDownload")) {
                        return checkForDownload(in, reply);
                    }
                case 17: 
                    if (method.equals("getContractAmdRpt")) {
                        return getContractAmdRpt(in, reply);
                    } else if (method.equals("getVarianceAllRpt")) {
                        return getVarianceAllRpt(in, reply);
                    }
                case 18: 
                    if (method.equals("getListEntitledRpt")) {
                        return getListEntitledRpt(in, reply);
                    }
                case 19: 
                    if (method.equals("getVariancePriceRpt")) {
                        return getVariancePriceRpt(in, reply);
                    } else if (method.equals("getInventoryListRpt")) {
                        return getInventoryListRpt(in, reply);
                    }
                case 20: 
                    if (method.equals("getContractAttachRpt")) {
                        return getContractAttachRpt(in, reply);
                    }
                case 21: 
                    if (method.equals("getdeletedUsersReport")) {
                        return getdeletedUsersReport(in, reply);
                    }
                case 22: 
                    if (method.equals("getContractPlanningRpt")) {
                        return getContractPlanningRpt(in, reply);
                    } else if (method.equals("getBAReportsbyModTypes")) {
                        return getBAReportsbyModTypes(in, reply);
                    }
                case 23: 
                    if (method.equals("getReverificationReport")) {
                        return getReverificationReport(in, reply);
                    }
                case 25: 
                    if (method.equals("getBAReportsbyFormNumbers")) {
                        return getBAReportsbyFormNumbers(in, reply);
                    }
                case 27: 
                    if (method.equals("getAllBAModificationReports")) {
                        return getAllBAModificationReports(in, reply);
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
    
    private OutputStream _get_EJBHome(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBHome result = target.getEJBHome();
        OutputStream out = reply.createReply();
        Util.writeRemoteObject(out,result);
        return out;
    }
    
    private OutputStream _get_primaryKey(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Object result = target.getPrimaryKey();
        OutputStream out = reply.createReply();
        Util.writeAny(out,result);
        return out;
    }
    
    private OutputStream remove(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        try {
            target.remove();
        } catch (RemoveException ex) {
            String id = "IDL:javax/ejb/RemoveEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,RemoveException.class);
            return out;
        }
        OutputStream out = reply.createReply();
        return out;
    }
    
    private OutputStream _get_handle(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Handle result = target.getHandle();
        OutputStream out = reply.createReply();
        Util.writeAbstractObject(out,result);
        return out;
    }
    
    private OutputStream isIdentical(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBObject arg0 = (EJBObject) in.read_Object(EJBObject.class);
        boolean result = target.isIdentical(arg0);
        OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private OutputStream getContractAttachRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ContractAttachmentReportCustomDTO arg0 = (ContractAttachmentReportCustomDTO) in.read_value(ContractAttachmentReportCustomDTO.class);
        ContractAttachmentReportCustomDTO result;
        try {
            result = target.getContractAttachRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ContractAttachmentReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getContractPlanningRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ContractPlanningReportCustomDTO arg0 = (ContractPlanningReportCustomDTO) in.read_value(ContractPlanningReportCustomDTO.class);
        ContractPlanningReportCustomDTO result;
        try {
            result = target.getContractPlanningRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ContractPlanningReportCustomDTO.class);
        return out;
    }
    
    private OutputStream listProposals(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ReportsCustomDTO arg0 = (ReportsCustomDTO) in.read_value(ReportsCustomDTO.class);
        ReportsCustomDTO result;
        try {
            result = target.listProposals(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ReportsCustomDTO.class);
        return out;
    }
    
    private OutputStream getContractAmdRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ContractAmendmentReportCustomDTO arg0 = (ContractAmendmentReportCustomDTO) in.read_value(ContractAmendmentReportCustomDTO.class);
        ContractAmendmentReportCustomDTO result;
        try {
            result = target.getContractAmdRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ContractAmendmentReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getCompareTPRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        CompareTPReportCustomDTO arg0 = (CompareTPReportCustomDTO) in.read_value(CompareTPReportCustomDTO.class);
        CompareTPReportCustomDTO result;
        try {
            result = target.getCompareTPRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,CompareTPReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getVarianceAllRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        VarianceRptCustomDTO arg0 = (VarianceRptCustomDTO) in.read_value(VarianceRptCustomDTO.class);
        VarianceRptCustomDTO result;
        try {
            result = target.getVarianceAllRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,VarianceRptCustomDTO.class);
        return out;
    }
    
    private OutputStream getVariancePriceRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        VarianceRptCustomDTO arg0 = (VarianceRptCustomDTO) in.read_value(VarianceRptCustomDTO.class);
        VarianceRptCustomDTO result;
        try {
            result = target.getVariancePriceRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,VarianceRptCustomDTO.class);
        return out;
    }
    
    private OutputStream getDeletedSWORpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        DeletedSWOReportCustomDTO arg0 = (DeletedSWOReportCustomDTO) in.read_value(DeletedSWOReportCustomDTO.class);
        DeletedSWOReportCustomDTO result;
        try {
            result = target.getDeletedSWORpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,DeletedSWOReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getListEntitledRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ListEntitledPricesReportCustomDTO arg0 = (ListEntitledPricesReportCustomDTO) in.read_value(ListEntitledPricesReportCustomDTO.class);
        ListEntitledPricesReportCustomDTO result;
        try {
            result = target.getListEntitledRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ListEntitledPricesReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getInventoryListRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        InventoryListReportCustomDTO arg0 = (InventoryListReportCustomDTO) in.read_value(InventoryListReportCustomDTO.class);
        InventoryListReportCustomDTO result;
        try {
            result = target.getInventoryListRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,InventoryListReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getSysplexRpt(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        SysplexReportCustomDTO arg0 = (SysplexReportCustomDTO) in.read_value(SysplexReportCustomDTO.class);
        SysplexReportCustomDTO result;
        try {
            result = target.getSysplexRpt(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,SysplexReportCustomDTO.class);
        return out;
    }
    
    private OutputStream checkForDownload(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ProposalCustomDTO arg0 = (ProposalCustomDTO) in.read_value(ProposalCustomDTO.class);
        boolean result;
        try {
            result = target.checkForDownload(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private OutputStream getReverificationReport(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ReverificationReportCustomDTO arg0 = (ReverificationReportCustomDTO) in.read_value(ReverificationReportCustomDTO.class);
        ReverificationReportCustomDTO result;
        try {
            result = target.getReverificationReport(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ReverificationReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getdeletedUsersReport(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        DeletedUsersReportCustomDTO arg0 = (DeletedUsersReportCustomDTO) in.read_value(DeletedUsersReportCustomDTO.class);
        DeletedUsersReportCustomDTO result;
        try {
            result = target.getdeletedUsersReport(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,DeletedUsersReportCustomDTO.class);
        return out;
    }
    
    private OutputStream getAllBAReports(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BaseAgreementReportCustomDTO arg0 = (BaseAgreementReportCustomDTO) in.read_value(BaseAgreementReportCustomDTO.class);
        BaseAgreementReportsCustomDTO result;
        try {
            result = target.getAllBAReports(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BaseAgreementReportsCustomDTO.class);
        return out;
    }
    
    private OutputStream getAllBAModificationReports(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BaseAgreementReportCustomDTO arg0 = (BaseAgreementReportCustomDTO) in.read_value(BaseAgreementReportCustomDTO.class);
        BaseAgreementReportsCustomDTO result;
        try {
            result = target.getAllBAModificationReports(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BaseAgreementReportsCustomDTO.class);
        return out;
    }
    
    private OutputStream getBAReportsbyFormNumbers(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BaseAgreementReportCustomDTO arg0 = (BaseAgreementReportCustomDTO) in.read_value(BaseAgreementReportCustomDTO.class);
        BaseAgreementReportsCustomDTO result;
        try {
            result = target.getBAReportsbyFormNumbers(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BaseAgreementReportsCustomDTO.class);
        return out;
    }
    
    private OutputStream getBAReportsbyModTypes(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BaseAgreementReportCustomDTO arg0 = (BaseAgreementReportCustomDTO) in.read_value(BaseAgreementReportCustomDTO.class);
        BaseAgreementReportsCustomDTO result;
        try {
            result = target.getBAReportsbyModTypes(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BaseAgreementReportsCustomDTO.class);
        return out;
    }
}
