// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.ibm.isc.customerfulfillment.bhoppt.service.orgmgr;

import com.ibm.isc.customerfulfillment.bhoppt.domain.dto.UserProfileDomainDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ActivityLogCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.BPUserCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.CreateUserCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.NonBPUserCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.ReverificationCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.SigninCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.UserCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.dto.customdto.UsersCustomDTO;
import com.ibm.isc.customerfulfillment.bhoppt.projectutilities.exception.ServiceException;
import java.lang.Object;
import java.lang.String;
import java.lang.Throwable;
import java.rmi.Remote;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Tie;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.ORB;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.Delegate;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.ResponseHandler;
import org.omg.CORBA.portable.UnknownException;

public class _EJSRemoteStatelessUserManager_9088852f_Tie extends org.omg.CORBA_2_3.portable.ObjectImpl implements Tie {
    
    private EJSRemoteStatelessUserManager_9088852f target = null;
    private ORB orb = null;
    
    private static final String[] _type_ids = {
        "RMI:com.ibm.isc.customerfulfillment.bhoppt.service.orgmgr.UserManager:0000000000000000", 
        "RMI:javax.ejb.EJBObject:0000000000000000", 
        "RMI:com.ibm.websphere.csi.CSIServant:0000000000000000", 
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public void setTarget(Remote target) {
        this.target = (EJSRemoteStatelessUserManager_9088852f) target;
    }
    
    public Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return this;
    }
    
    public void deactivate() {
        if (orb != null) {
            orb.disconnect(this);
            _set_delegate(null);
        }
    }
    
    public ORB orb() {
        return _orb();
    }
    
    public void orb(ORB orb) {
        orb.connect(this);
    }
    
    public void _set_delegate(Delegate del) {
        super._set_delegate(del);
        if (del != null)
            orb = _orb();
        else
            orb = null;
    }
    
    public String[] _ids() { 
        return (String [] )  _type_ids.clone();
    }
    
    public OutputStream _invoke(String method, InputStream _in, ResponseHandler reply) throws SystemException {
        try {
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.charAt(4)) {
                case 65: 
                    if (method.equals("listAllSalesOrgs")) {
                        return listAllSalesOrgs(in, reply);
                    }
                case 66: 
                    if (method.equals("editBPUser")) {
                        return editBPUser(in, reply);
                    }
                case 69: 
                    if (method.equals("saveEditBPUser")) {
                        return saveEditBPUser(in, reply);
                    } else if (method.equals("saveEditNonBPUser")) {
                        return saveEditNonBPUser(in, reply);
                    }
                case 73: 
                    if (method.equals("signIn")) {
                        return signIn(in, reply);
                    }
                case 78: 
                    if (method.equals("editNonBPUser")) {
                        return editNonBPUser(in, reply);
                    }
                case 85: 
                    if (method.equals("listUsersInSalesOrg")) {
                        return listUsersInSalesOrg(in, reply);
                    }
                case 95: 
                    if (method.equals("_get_primaryKey")) {
                        return _get_primaryKey(in, reply);
                    } else if (method.equals("_get_handle")) {
                        return _get_handle(in, reply);
                    } else if (method.equals("_get_EJBHome")) {
                        return _get_EJBHome(in, reply);
                    }
                case 99: 
                    if (method.equals("getActivityLog")) {
                        return getActivityLog(in, reply);
                    }
                case 101: 
                    if (method.equals("isIdentical")) {
                        return isIdentical(in, reply);
                    } else if (method.equals("processCreateNewUser")) {
                        return processCreateNewUser(in, reply);
                    }
                case 115: 
                    if (method.equals("registerBPUser")) {
                        return registerBPUser(in, reply);
                    } else if (method.equals("registerNonBPUser")) {
                        return registerNonBPUser(in, reply);
                    } else if (method.equals("getUserProfile")) {
                        return getUserProfile(in, reply);
                    }
                case 116: 
                    if (method.equals("createBPUser")) {
                        return createBPUser(in, reply);
                    } else if (method.equals("createNonBPUser")) {
                        return createNonBPUser(in, reply);
                    } else if (method.equals("createNewUser")) {
                        return createNewUser(in, reply);
                    }
                case 118: 
                    if (method.equals("remove")) {
                        return remove(in, reply);
                    } else if (method.equals("removeUser")) {
                        return removeUser(in, reply);
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
    
    private OutputStream _get_EJBHome(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBHome result = target.getEJBHome();
        OutputStream out = reply.createReply();
        Util.writeRemoteObject(out,result);
        return out;
    }
    
    private OutputStream _get_primaryKey(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Object result = target.getPrimaryKey();
        OutputStream out = reply.createReply();
        Util.writeAny(out,result);
        return out;
    }
    
    private OutputStream remove(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        try {
            target.remove();
        } catch (RemoveException ex) {
            String id = "IDL:javax/ejb/RemoveEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,RemoveException.class);
            return out;
        }
        OutputStream out = reply.createReply();
        return out;
    }
    
    private OutputStream _get_handle(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Handle result = target.getHandle();
        OutputStream out = reply.createReply();
        Util.writeAbstractObject(out,result);
        return out;
    }
    
    private OutputStream isIdentical(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBObject arg0 = (EJBObject) in.read_Object(EJBObject.class);
        boolean result = target.isIdentical(arg0);
        OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private OutputStream createBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BPUserCustomDTO arg0 = (BPUserCustomDTO) in.read_value(BPUserCustomDTO.class);
        BPUserCustomDTO result;
        try {
            result = target.createBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream createNonBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        NonBPUserCustomDTO arg0 = (NonBPUserCustomDTO) in.read_value(NonBPUserCustomDTO.class);
        NonBPUserCustomDTO result;
        try {
            result = target.createNonBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,NonBPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream createNewUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        CreateUserCustomDTO arg0 = (CreateUserCustomDTO) in.read_value(CreateUserCustomDTO.class);
        CreateUserCustomDTO result;
        try {
            result = target.createNewUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,CreateUserCustomDTO.class);
        return out;
    }
    
    private OutputStream getActivityLog(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ActivityLogCustomDTO arg0 = (ActivityLogCustomDTO) in.read_value(ActivityLogCustomDTO.class);
        ActivityLogCustomDTO result;
        try {
            result = target.getActivityLog(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ActivityLogCustomDTO.class);
        return out;
    }
    
    private OutputStream editBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BPUserCustomDTO arg0 = (BPUserCustomDTO) in.read_value(BPUserCustomDTO.class);
        BPUserCustomDTO result;
        try {
            result = target.editBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream editNonBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        NonBPUserCustomDTO arg0 = (NonBPUserCustomDTO) in.read_value(NonBPUserCustomDTO.class);
        NonBPUserCustomDTO result;
        try {
            result = target.editNonBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,NonBPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream listUsersInSalesOrg(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        UsersCustomDTO arg0 = (UsersCustomDTO) in.read_value(UsersCustomDTO.class);
        UsersCustomDTO result;
        try {
            result = target.listUsersInSalesOrg(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,UsersCustomDTO.class);
        return out;
    }
    
    private OutputStream registerBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BPUserCustomDTO arg0 = (BPUserCustomDTO) in.read_value(BPUserCustomDTO.class);
        BPUserCustomDTO result;
        try {
            result = target.registerBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream registerNonBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        NonBPUserCustomDTO arg0 = (NonBPUserCustomDTO) in.read_value(NonBPUserCustomDTO.class);
        NonBPUserCustomDTO result;
        try {
            result = target.registerNonBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,NonBPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream processCreateNewUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        CreateUserCustomDTO arg0 = (CreateUserCustomDTO) in.read_value(CreateUserCustomDTO.class);
        CreateUserCustomDTO result;
        try {
            result = target.processCreateNewUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,CreateUserCustomDTO.class);
        return out;
    }
    
    private OutputStream saveEditBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        BPUserCustomDTO arg0 = (BPUserCustomDTO) in.read_value(BPUserCustomDTO.class);
        BPUserCustomDTO result;
        try {
            result = target.saveEditBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,BPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream removeUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        UserCustomDTO arg0 = (UserCustomDTO) in.read_value(UserCustomDTO.class);
        UserCustomDTO result;
        try {
            result = target.removeUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,UserCustomDTO.class);
        return out;
    }
    
    private OutputStream saveEditNonBPUser(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        NonBPUserCustomDTO arg0 = (NonBPUserCustomDTO) in.read_value(NonBPUserCustomDTO.class);
        NonBPUserCustomDTO result;
        try {
            result = target.saveEditNonBPUser(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,NonBPUserCustomDTO.class);
        return out;
    }
    
    private OutputStream signIn(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        SigninCustomDTO arg0 = (SigninCustomDTO) in.read_value(SigninCustomDTO.class);
        SigninCustomDTO result;
        try {
            result = target.signIn(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,SigninCustomDTO.class);
        return out;
    }
    
    private OutputStream getUserProfile(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        String arg0 = (String) in.read_value(String.class);
        UserProfileDomainDTO result;
        try {
            result = target.getUserProfile(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,UserProfileDomainDTO.class);
        return out;
    }
    
    private OutputStream listAllSalesOrgs(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        ReverificationCustomDTO arg0 = (ReverificationCustomDTO) in.read_value(ReverificationCustomDTO.class);
        ReverificationCustomDTO result;
        try {
            result = target.listAllSalesOrgs(arg0);
        } catch (ServiceException ex) {
            String id = "IDL:com/ibm/isc/customerfulfillment/bhoppt/projectutilities/_exception/ServiceEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,ServiceException.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,ReverificationCustomDTO.class);
        return out;
    }
}
